services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: seteirmaos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha
    volumes:
      - ./backend/dbf:/app/backend/dbf    # mapeia todos os DBF
    ports:
      - '5432:5432'
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: sua_senha
      DB_NAME: seteirmaos
      JWT_SECRET: seu_segredo_aqui
    ports:
      - '5000:5000'