version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: seteirmaos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: \Sete@2025
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=\Sete@2025
      - DB_NAME=seteirmaos
volumes:
  pgdata:
