version: '3.8'
services:
  db:
    image: postgres:13-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db-data: